# Generated by Django 5.0 on 2024-02-01 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dept",
            fields=[
                ("Dept_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Dept_Name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "Username",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("Password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("Subject_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Subject_Name", models.CharField(max_length=255)),
                ("Sem", models.IntegerField()),
                (
                    "Dept_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.dept"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "Faculty_ID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("Name", models.CharField(max_length=255)),
                ("Qualifications", models.CharField(max_length=255)),
                ("Papers_Published", models.IntegerField()),
                ("Phone_No", models.CharField(max_length=10)),
                ("Email", models.EmailField(max_length=255)),
                (
                    "Dept_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.dept"
                    ),
                ),
                (
                    "Subject_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "USN",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("Name", models.CharField(max_length=255)),
                ("Gender", models.CharField(max_length=6)),
                ("Phone_No", models.CharField(max_length=10)),
                ("Email", models.EmailField(max_length=255)),
                ("Joining_Year", models.IntegerField()),
                (
                    "Dept_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.dept"
                    ),
                ),
                (
                    "Sem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sem_students",
                        to="LMS.course",
                    ),
                ),
                (
                    "Subject_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Marks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Internal_Marks", models.IntegerField()),
                ("Assignment_Marks", models.IntegerField()),
                ("Seminar_Marks", models.IntegerField()),
                ("External_Marks", models.IntegerField()),
                ("Final_Marks", models.IntegerField()),
                ("Performance", models.IntegerField()),
                (
                    "Sem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sem_marks",
                        to="LMS.course",
                    ),
                ),
                (
                    "Subject_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.course"
                    ),
                ),
                (
                    "USN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Extra_Curricular",
            fields=[
                ("Event_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Event_Name", models.CharField(max_length=255)),
                ("Circulars", models.CharField(max_length=255)),
                ("Extra_Curricular_Score", models.IntegerField()),
                (
                    "Coordinator_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.faculty"
                    ),
                ),
                (
                    "USN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField()),
                ("Attendance_status", models.CharField(max_length=10)),
                ("Behaviour_Score", models.IntegerField()),
                ("Attendance_Score", models.IntegerField()),
                (
                    "Subject_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.course"
                    ),
                ),
                (
                    "USN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.student"
                    ),
                ),
            ],
        ),
    ]
