# Generated by Django 5.0 on 2024-03-10 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dept",
            fields=[
                ("Dept_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Dept_Name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("Subject_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Subject_Name", models.CharField(max_length=255)),
                (
                    "Sem",
                    models.CharField(
                        choices=[
                            ("1", "1st Semester"),
                            ("2", "2nd Semester"),
                            ("3", "3rd Semester"),
                            ("4", "4th Semester"),
                            ("5", "5th Semester"),
                            ("6", "6th Semester"),
                            ("7", "7th Semester"),
                            ("8", "8th Semester"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "Dept_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.dept"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "Faculty_ID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("Name", models.CharField(max_length=255)),
                (
                    "Qualifications",
                    models.CharField(
                        choices=[
                            ("b.e", "B.E"),
                            ("b.sc", "B.Sc"),
                            ("m.tech", "M.Tech"),
                            ("m.sc", "M.Sc"),
                            ("phd", "PhD"),
                        ],
                        max_length=6,
                    ),
                ),
                ("Papers_Published", models.IntegerField()),
                ("Phone_No", models.CharField(max_length=10)),
                ("Email", models.EmailField(max_length=255)),
                (
                    "Dept_ID",
                    models.ManyToManyField(related_name="faculty_depts", to="LMS.dept"),
                ),
                (
                    "Subject_ID",
                    models.ManyToManyField(
                        related_name="faculty_subjects", to="LMS.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_timestamp", models.DateTimeField(auto_now_add=True)),
                ("logout_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-login_timestamp"],},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "USN",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("Name", models.CharField(max_length=255)),
                (
                    "Gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=6,
                    ),
                ),
                ("Phone_No", models.CharField(max_length=10)),
                ("Email", models.EmailField(max_length=255)),
                ("Joining_Year", models.IntegerField()),
                (
                    "Dept_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.dept"
                    ),
                ),
                (
                    "Sem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sem_students",
                        to="LMS.course",
                    ),
                ),
                (
                    "Subject_ID",
                    models.ManyToManyField(
                        related_name="student_subjects", to="LMS.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Marks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Internal_Marks", models.IntegerField()),
                ("Assignment_Marks", models.IntegerField()),
                ("Seminar_Marks", models.IntegerField()),
                ("External_Marks", models.IntegerField()),
                ("Final_Marks", models.IntegerField()),
                ("Performance", models.IntegerField(null=True)),
                (
                    "Sem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sem_marks",
                        to="LMS.course",
                    ),
                ),
                (
                    "Subject_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.course"
                    ),
                ),
                (
                    "USN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Extra_Curricular",
            fields=[
                ("Event_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Event_Name", models.CharField(max_length=255)),
                ("Circulars", models.CharField(max_length=255)),
                ("Extra_Curricular_Score", models.IntegerField()),
                (
                    "Coordinator_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.faculty"
                    ),
                ),
                (
                    "USN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField()),
                ("Attendance_status", models.CharField(max_length=10)),
                ("Behaviour_Score", models.IntegerField(null=True)),
                ("Attendance_Score", models.IntegerField(null=True)),
                (
                    "Subject_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.course"
                    ),
                ),
                (
                    "USN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LMS.student"
                    ),
                ),
            ],
        ),
    ]
