# Generated by Django 5.0 on 2024-03-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="Attendance_status",
            field=models.CharField(
                choices=[("P", "Present"), ("AB", "Absent")], max_length=2
            ),
        ),
    ]
