# Generated by Django 5.0 on 2024-02-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0003_faculty_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course", name="Sem", field=models.CharField(max_length=255),
        ),
    ]
