# Generated by Django 5.0 on 2024-02-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0005_loginhistory_delete_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="Attendance_Score",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="Behaviour_Score",
            field=models.IntegerField(null=True),
        ),
    ]
