# Generated by Django 5.0 on 2024-02-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0006_alter_attendance_attendance_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marks",
            name="Performance",
            field=models.IntegerField(null=True),
        ),
    ]
