# Generated by Django 5.0 on 2024-02-22 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0007_alter_marks_performance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Sem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sem_students",
                to="LMS.course",
            ),
        ),
    ]
