# Generated by Django 5.0 on 2024-02-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0008_alter_student_sem"),
    ]

    operations = [
        migrations.RemoveField(model_name="faculty", name="user",),
        migrations.RemoveField(model_name="student", name="user",),
    ]
