# Generated by Django 5.0 on 2024-02-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0009_remove_faculty_user_remove_student_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=6,
            ),
        ),
        migrations.RemoveField(model_name="student", name="Subject_ID",),
        migrations.AddField(
            model_name="student",
            name="Subject_ID",
            field=models.ManyToManyField(
                related_name="student_subjects", to="LMS.course"
            ),
        ),
    ]
