# Generated by Django 5.0 on 2024-02-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0010_alter_student_gender_remove_student_subject_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="Qualifications",
            field=models.CharField(
                choices=[
                    ("b.e", "B.E"),
                    ("b.sc", "B.Sc"),
                    ("m.tech", "M.Tech"),
                    ("m.sc", "M.Sc"),
                    ("phd", "PhD"),
                ],
                max_length=6,
            ),
        ),
    ]
