# Generated by Django 5.0.1 on 2024-02-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0011_alter_faculty_qualifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Joining_Year",
            field=models.IntegerField(verbose_name=4),
        ),
    ]
