# Generated by Django 5.0 on 2024-02-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0011_alter_faculty_qualifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="Sem",
            field=models.CharField(
                choices=[
                    ("1", "1st Semester"),
                    ("2", "2nd Semester"),
                    ("3", "3rd Semester"),
                    ("4", "4th Semester"),
                    ("5", "5th Semester"),
                    ("6", "6th Semester"),
                    ("7", "7th Semester"),
                    ("8", "8th Semester"),
                ],
                max_length=1,
            ),
        ),
    ]
