# Generated by Django 5.0.1 on 2024-02-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0012_alter_student_joining_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Joining_Year",
            field=models.IntegerField(max_length=4),
        ),
    ]
