# Generated by Django 5.0.1 on 2024-02-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0012_alter_course_sem"),
        ("LMS", "0016_alter_student_joining_year"),
    ]

    operations = []
