# Generated by Django 5.0.1 on 2024-02-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0017_merge_20240225_1356"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Joining_Year",
            field=models.IntegerField(),
        ),
    ]
