# Generated by Django 5.0.1 on 2024-03-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0018_alter_student_joining_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="Subject_ID",
        ),
        migrations.AddField(
            model_name="faculty",
            name="Subject_ID",
            field=models.ManyToManyField(
                related_name="faculty_subjects", to="LMS.course"
            ),
        ),
    ]
