# Generated by Django 5.0.1 on 2024-03-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0021_alter_faculty_subject_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="Subject_ID",
        ),
        migrations.AddField(
            model_name="faculty",
            name="Subject_ID",
            field=models.ManyToManyField(to="LMS.course"),
        ),
    ]
